public class Lab3{
    public static void main(String... args){
        
        ServiceWords from = ServiceWords.FROM;
        ServiceWords by = ServiceWords.BY;
        ServiceWords in = ServiceWords.IN;
        ServiceWords under = ServiceWords.UNDER;
        ServiceWords down = ServiceWords.DOWN;
        ServiceWords not = ServiceWords.NOT;
        ServiceWords but = ServiceWords.BUT;
        ServiceWords and = ServiceWords.AND;
        ServiceWords to = ServiceWords.TO;
        ServiceWords that = ServiceWords.THAT;
        ServiceWords below = ServiceWords.BELOW;
        ServiceWords dont = ServiceWords.DONT;
        Shorties znaika = new Shorties("Znaika");
        Shorties zvezdochkin = new Shorties("Professor Zvezdochkin");
        Shorties group = new Shorties("Shorties");
        Clothes bulkySpacesuits = new Clothes("bulky spacesuits");
        znaika.setClothes(bulkySpacesuits);
        zvezdochkin.setClothes(bulkySpacesuits);
        group.setClothes(bulkySpacesuits);
        Cave cave = new Cave();
        Experience experience = new Experience("this");
        Activities attended = Activities.ATTENDED;
        attended.setExtension(experience);
        Activities separated = Activities.SEPARATED;
        Moment moment = new Moment("this");
        separated.setExtension(moment);
        Activities gotUp = Activities.GOT_UP;
        Activities swimming = Activities.SWIMMING;
        VarietyOfPoses varietyOfPoses = new VarietyOfPoses("in a wide");
        swimming.setExtension(varietyOfPoses);
        Activities tried = Activities.TRIED;
        Strongly strongly = new Strongly();
        tried.setExtension(strongly);
        Activities goDown = Activities.GO_DOWN;
        Attempts attempts = new Attempts("were unsuccessful");
        Activities being = Activities.BEING;
        Correct correct = new Correct();
        Activities calculate = Activities.CALCULATE;
        calculate.setExtension(correct);
        BodyMovements bodyMovements = new BodyMovements("their");
        Activities use = Activities.USE;
        ReactiveForces reactiveForce = new ReactiveForces("for movement");
        use.setExtension(reactiveForce);
        Fact fact = new Fact("that", "caused");
        Confusion confusion = new Confusion("general");
        Activities exposed = Activities.EXPOSED;
        Reason reason = new Reason("for some");
        exposed.setExtension(reason);
        Effect effect = new Effect("weightlessness");
        Activities continued = Activities.CONTINUED;
        Happened happened = new Happened("like nothing");
        continued.setExtension(happened);
        Device device = new Device("of weightlessness", "from place to place");
        Activities transferred = Activities.TRANSFERRED;
        transferred.setExtension(device);
        Activities departed = Activities.DEPARTED;
        Activities checked = Activities.CHECKED;
        Scale scale = new Scale("a spring");
        Thing thing = new Thing("change", "in gravity");
        Support support = new Support(scale);
        checked.setExtension(support);
        
        
        System.out.print(group.getName() + " ");
        group.setActivity(attended);
        group.setSubject(experience);
        System.out.print(group.getActivity() + " ");
        group.setActivity(Activities.SEPARATED);
        System.out.print(group.getActivity() + " ");
        System.out.print(from.getServiceWord() + " ");
        cave.setArea(Area.BOTTOM);
        System.out.print(cave.getPlace() + " ");
        System.out.print(and.getServiceWord() + " ");
        group.setActivity(gotUp);
        System.out.print(group.getActivity() + ". ");
        group.setActivity(swimming);
        System.out.print(group.getActivity() + " ");
        System.out.print(under.getServiceWord() + " ");
        cave.setArea(Area.CEILING);
        System.out.print(cave.getPlace() + " ");
        group.setName("they");
        System.out.print(group.getName() + " ");
        group.setActivity(tried);
        System.out.print(group.getActivity() + " ");
        group.setActivity(tried);
        System.out.print(group.getActivity() + " ");
        group.setActivity(goDown);
        System.out.print(group.getActivity() + " ");
        System.out.print(but.getServiceWord() + " ");
        System.out.print(attempts.getAttempts() + ". ");
        group.setActivity(being);
        System.out.print(group.getActivity() + " ");
        System.out.print(group.getClothes() + " ");
        System.out.print(group.getName() + " ");
        System.out.print(Activities.COULD.getFullActivity() + " ");
        System.out.print(not.getServiceWord() + " ");
        group.setActivity(calculate);
        System.out.print(group.getActivity() + " ");
        group.setSubject(bodyMovements);
        System.out.print(group.getSubject() + " ");
        System.out.print(and.getServiceWord() + " ");
        group.setActivity(use);
        System.out.print(group.getActivity() + ". ");
        System.out.print(fact.getFact() + " ");
        System.out.print(confusion.getConfusion() + " ");
        System.out.print(that.getServiceWord() + " ");
        znaika.setActivity(exposed);
        zvezdochkin.setActivity(exposed);
        System.out.print(znaika.getName() + " ");
        System.out.print(dont.getServiceWord() + " ");
        System.out.print(znaika.getActivity() + " ");
        System.out.print(and.getServiceWord() + " ");
        System.out.print(zvezdochkin.getName() + " ");
        System.out.print(dont.getServiceWord() + " ");
        System.out.print(zvezdochkin.getActivity() + " ");
        System.out.print(effect.getEffect() + " ");
        System.out.print(and.getServiceWord() + " ");
        znaika.setActivity(continued);
        zvezdochkin.setActivity(continued);
        System.out.print(znaika.getName() + " ");
        System.out.print(znaika.getActivity() + " ");
        System.out.print(and.getServiceWord() + " ");
        System.out.print(zvezdochkin.getName() + " ");
        System.out.print(zvezdochkin.getActivity() + " ");
        znaika.setActivity(Activities.WORK);
        zvezdochkin.setActivity(Activities.WORK);
        System.out.print(znaika.getName() + " ");
        System.out.print(znaika.getActivity() + " ");
        System.out.print(and.getServiceWord() + " ");
        System.out.print(zvezdochkin.getName() + " ");
        System.out.print(zvezdochkin.getActivity() + " ");
        System.out.print(below.getServiceWord() + ". ");
        zvezdochkin.setActivity(transferred);
        znaika.setActivity(transferred);
        System.out.print(znaika.getName() + " ");
        System.out.print(znaika.getActivity() + " ");
        System.out.print(and.getServiceWord() + " ");
        System.out.print(zvezdochkin.getName() + " ");
        System.out.print(zvezdochkin.getActivity() + ", ");
        zvezdochkin.setActivity(departed);
        znaika.setActivity(departed);
        System.out.print(znaika.getName() + " ");
        System.out.print(znaika.getActivity() + " ");
        System.out.print(and.getServiceWord() + " ");
        System.out.print(zvezdochkin.getName() + " ");
        System.out.print(zvezdochkin.getActivity() + ", ");
        System.out.print(to.getServiceWord() + " ");
        cave.setArea(Area.FAR_CORNERS);
        System.out.print(cave.getPlace());
        zvezdochkin.setActivity(checked);
        znaika.setActivity(checked);
        System.out.print(znaika.getName() + " ");
        System.out.print(znaika.getActivity() + " ");
        System.out.print(thing.getName() + " ");
        System.out.print(and.getServiceWord() + " ");
        System.out.print(zvezdochkin.getName() + " ");
        System.out.print(zvezdochkin.getActivity() + " ");
        System.out.print(thing.getName() + ".");
    }
}